services:
  - type: web
    name: aanandbavan-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://srenewaanandabavan_db_user:9597535555R@srenewaanandbavan.3cbwvyn.mongodb.net/?appName=srenewaanandbavan
      - key: DATABASE_NAME
        value: srenewaanandbavan
      - key: ADMIN_EMAIL
        value: srenewaanandbavan@gmail.com
